name: E2E Tests
on:
  pull_request:
    branches: [dev, main, feature/**]
  workflow_dispatch:
    inputs:
      test_url:
        description: 'Application URL to run E2E tests against (defaults to local, in order to test changes that are present in the PR)'
        required: true
        type: string
        default: 'http://localhost:8888'
      api_url:
        description: 'API URL to use (optional)'
        required: false
        type: string

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set API URL and Test Credentials
        env:
          E2E_API_KEY_PROD: ${{ secrets.E2E_API_KEY_PROD }}
          E2E_API_KEY_DEV: ${{ secrets.E2E_API_KEY_DEV }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          TEST_URL: ${{ github.event.inputs.test_url }}
          API_URL: ${{ github.event.inputs.api_url }}

        run: bash .github/scripts/set-e2e-env.sh

      - name: Run Playwright tests
        env:
          E2E_PASSWORD_AUTH_EMAIL_PROD: ${{ secrets.E2E_PASSWORD_AUTH_EMAIL_PROD }}
          E2E_PASSWORD_AUTH_PASSWORD_PROD: ${{ secrets.E2E_PASSWORD_AUTH_PASSWORD_PROD }}
          E2E_PASSWORD_AUTH_EMAIL_TEST: ${{ secrets.E2E_PASSWORD_AUTH_EMAIL_TEST }}
          E2E_PASSWORD_AUTH_PASSWORD_TEST: ${{ secrets.E2E_PASSWORD_AUTH_PASSWORD_TEST }}
          E2E_PW_RESET_EMAIL_PROD: ${{ secrets.E2E_PW_RESET_EMAIL_PROD }}
          E2E_PW_RESET_EMAIL_TEST: ${{ secrets.E2E_PW_RESET_EMAIL_TEST }}
          E2E_SIGNUP_EMAIL_PROD: ${{ secrets.E2E_SIGNUP_EMAIL_PROD }}
          E2E_SIGNUP_EMAIL_TEST: ${{ secrets.E2E_SIGNUP_EMAIL_TEST }}
          MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}

        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
